version: '3.8'

services:
  worx-core1:
    image: ${WORX_NODE_DOCKER_NAME}
    ports:
      - "8080:8080"
    networks:
      - backend
    restart: always
    env_file:
      - worx-core.env
    depends_on:
      - db

  worx-web-ui1:
    image: ${WEB_UI_DOCKER_NAME}
    ports:
      - "8081:80"
    restart: always
    env_file:
      - worx-web-ui.env

  db:
    image: mysql:8.0.28
    env_file:
      - mysql.env
    ports:
      - "3306"
    networks:
      - backend
    restart: always
    volumes:
      - ./.docker/db/data:/var/lib/mysql
      - ./.docker/db/conf.d:/etc/mysql/conf.d/
      - ./.docker/db/log:/var/log/mysql
      - ./.docker/db/backup:/backup

networks:
  backend:
    name: backend_network
    driver: bridge